### ISSUE TITLE
email optional argument and nohyperref documentclass option

### ISSUE THREAD

**Issue by pfasante** [Cryptosaurus/iacrtrans#11]
When using the `nohyperref` documentclass option the optional argument of the `\email` macro seems to be ignored.

**Comment by Cryptosaurus** [comment]
Indeed, the optional argument to `\email` is used to create an hyperlink, what would you use it for when hyperref is not available?

(Actually, there seem to be a few other things broken with `nohyperref`, I'll try to fix them)

**Comment by Cryptosaurus** [comment]
Closing issue, let me know if there's still something to be fixed...
