### ISSUE TITLE
script hints

### ISSUE THREAD

**Issue by bbbrumley** [Cryptosaurus/iacrtrans#21]
https://github.com/Cryptosaurus/iacrtrans/blob/ad3591015f1c284a3b0d6faf1c238b820448c17e/iacrdoc.tex#L117-L128

Any other documentation on how these hints work?

For example, hints how to split first / last names?

**Comment by jowlo** [comment]
As i argued in #20, these hints are for internal use only. We only use them if our automatic system for some reason does not work as expected.
I don't think that authors should have to deal with this at all, as you also do not know the code that parses these hints.

So, as the guy who actually compiles the issues for TCHES, i would recommend you just remove these and/or don't worry about it (as you would with #20 merged).
But getting a pull request merged in this repository sadly takes a lot of time.

**Comment by Cryptosaurus** [comment]
@pfasante How do you use title hints when editing ToSC?  Is it okay to remove them following #20?

**Comment by pfasante** [comment]
Yes that would be ok for ToSC

**Comment by jowlo** [comment]
Since #20 is merged, can we agree on closing this one?

**Comment by bbbrumley** [comment]
Yea totally I never followed up! Thanks for the clarification -- closing
