### ISSUE TITLE
Compilation error in submission mode

### ISSUE THREAD

**Issue by dstebila** [Cryptosaurus/iacrtrans#22]
When compiling even the most basic document in submission mode using the iacrtrans template, I get an error.  When I switch to final mode, there error goes away.

Here's a sample document:

```latex
\documentclass[journal=tches,submission]{iacrtrans}

\title{Test title}
\author{Author name}
\institute{University of Whatever}

\begin{document}

\maketitle

Foo

\end{document}
```

Here's the error I get:

```
./main.tex:13: Extra \else.
<output> ...else \LineNoLaTeXOutput \fi \fi \else 
                                                  \MakeLineNo \fi }
l.13 \end{document}
```

I'm using TexLive 2019 on macOS, with all updates installed.

**Comment by jowlo** [comment]
Yes, we must have introduced some errors to the .cls file and not tested the submission mode. A fix will be available soon.
