### ISSUE TITLE
could you please provide a template for overleaf?

### ISSUE THREAD

**Issue by AnShukun** [Cryptosaurus/iacrtrans#25]
I have downloaded the template for latex and upload it in overleaf but the "reference" section has vanished. There seems to lack a ".bib" file.

**Comment by mcsmonk** [comment]
You can create your own new bib file or use cryptobib [link](https://cryptobib.di.ens.fr/)

**Comment by AnShukun** [comment]
Thanks, I have solved the problem

**Comment by Cryptosaurus** [comment]
Closing.
