### ISSUE TITLE
margin width and todo notes

### ISSUE THREAD

**Issue by pfasante** [Cryptosaurus/iacrtrans#5]
The todonotes package does not work well with the margins from iacrtrans class.
Here is a MWE:
```
\documentclass[submission]{iacrtrans}

\usepackage{todonotes}

\begin{document}
Hello world.\todo{fix margin for todo notes}
\end{document}
```
The todo note in the margin does not correctly break at the end of the page.

**Comment by Cryptosaurus** [comment]
Thanks for pointing this out!
It should be fixed by 8c101ae9db1ab883d3e7c43abd53d2e1c8f04d2d
