### ISSUE TITLE
Add an Option to handle both journals, ToSC and TCHES

### ISSUE THREAD

**Issue by pfasante** [Cryptosaurus/iacrtrans#7]
The templates for ToSC and TCHES are basically the same, as far as I know.
So maybe we should add an documentclass option, to switch between the two.
What needs to be changed is the Transactions on... string and I guess nothing else?

**Comment by jowlo** [comment]
Sounds like a good idea.
We could alternatively source this from the settings file, as we do with DOIs, issn, etc.

Caveat for both approaches:
 * a little less convenient for authors, as they can not simply download and use a `.cls`-file. Using a sensible default will probably solve this.
